#!/bin/bash
action=$CNAB_ACTION
name=$CNAB_INSTALLATION_NAME

cd /cnab/app/
docker-compose --version

case $action in
    build)
    echo "Executing build steps..."
    ;;
    install)
    echo "Install action"
    echo "executing docker-compose up"
    docker-compose up -d
    ;;
    uninstall)
    echo "uninstall action"
    echo "executing docker-compose down"
    docker-compose down
    ;;
    upgrade)
    echo "Upgrade action"
    ;;
    downgrade)
    echo "Downgrade action"
    ;;
    status)
    echo "Status action"
    ;;
    *)
    echo "No action for $action"
    ;;
esac
echo "Action $action complete for $name"