# FROM alpine:latest
# FROM node:10.15.0-alpine
FROM docker:latest

RUN apk update
RUN apk add -u bash && \
    apk add --update nodejs nodejs-npm && \
    npm install -g aws-cdk && \
    npm install -g typescript

RUN mkdir -p /cnab/app

COPY Dockerfile /cnab/Dockerfile
COPY app /cnab/app

RUN chmod +x /cnab/app/run_invocation

WORKDIR /cnab/app/ts_cdk

ENTRYPOINT ["/cnab/app/run_invocation"]