#!/bin/bash
action=$CNAB_ACTION
name=$CNAB_INSTALLATION_NAME

# echo "DYNAMODB_ENDPOINT_URL is: ${DYNAMODB_ENDPOINT_URL}"

case $action in
   
    install)
    echo "Install action"
    if [ "$localEnvironment" = true ]; then
        cd /cnab/app/docker-compose
        echo "executing docker-compose up"
        docker-compose up -d
    fi

    if [ "$awsEnvironment" = true ]; then
        cd /cnab/app/ts_cdk
        echo "Executng cdk deploy"
        # cdk diff
        cdk bootstrap
        cdk deploy
    fi


    ;;

    uninstall)
    echo "uninstall action"
    if [ "$localEnvironment" = true ]; then
        cd /cnab/app/docker-compose
        echo "executing docker-compose down"
        docker-compose down
    fi

    if [ "$awsEnvironment" = true ]; then
        cd /cnab/app/ts_cdk
        echo "Executing cdk destroy "
        cdk destroy --force
    fi

    ;;

    upgrade)
    echo "Upgrade action"
    ;;

    downgrade)
    echo "Downgrade action"
    ;;

    status)
    echo "Status action"
    ;;

    *)
    echo "No action for $action"
    ;;
esac

echo "Action $action complete for $name"