#!/bin/bash

case ${1} in
    install)

    docker run -d -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_DEFAULT_REGION raviydevops/cdk_crud:1.0.0 install
    ;;

    uninstall)
    docker run -d -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_DEFAULT_REGION raviydevops/cdk_crud:1.0.0 uninstall
    ;;

    upgrade)
    echo "Upgrade action"
    ;;

    downgrade)
    echo "Downgrade action"
    ;;

    status)
    echo "Status action"
    ;;

    *)
    echo "No action for $action"
    ;;
esac

echo "Action ${1} completed"